ecommerce_village_of_electron/core/urls.py
from django.urls import path

from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    SearchView,
    product_category_list,
    ProductByCategory,
    thank_veiw

)
#    path('books/<publisher>/', PublisherBookList.as_view()),

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('thanks', thank_veiw, name='thanks'),
    path('search/', SearchView.as_view(), name='search'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('category-product/<category>/',
         ProductByCategory.as_view(), name='category'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
]

ecommerce_village_of_electron/core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse


CATEGORY_CHOICES = (
    ('L', 'Laptops'),
    ('SM', 'Smart phones'),
    ('T', 'Tablets')
)

CITY_CHOICES = (
    ('Amman', 'Amman'),
    ('Irbid', 'Irbid'),
    ('Zarqaa', 'Zarqaa'),
    ('Aqaba', 'Aqaba'),
    ('Alkarak', 'Alkarak'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class CategoryProduct(models.Model):

    category_product = models.CharField(choices=CATEGORY_CHOICES, max_length=2)

    def __str__(self):
        return self.category_product


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    category = models.ForeignKey(
        to='CategoryProduct', on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    image_tow = models.ImageField(blank=True, null=True)
    image_three = models.ImageField(blank=True, null=True)
    image_four = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class Tag(models.Model):
    tag = models.CharField(max_length=255)

    def __str__(self):
        return self.tag


class ProductTags(models.Model):
    tag_name = models.ManyToManyField(to='Tag')
    tag_product = models.OneToOneField(
        to='Item', on_delete=models.CASCADE, null=True, blank=True, unique=True)

    # def __str__(self):
    #     return self.tag_name


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_final_price(self):
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class CheckoutModel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    address = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(choices=CITY_CHOICES, max_length=10)
    phone_number = models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.user.username

ecommerce_village_of_electron/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

ecommerce_village_of_electron/templates/category.html
{% extends "home.html" %}


{% for item in products %}
<div class="col-lg-3 col-md-6 mb-4">

    <div class="card">

        <div class="view overlay">
            {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                class="card-img-top" {% endcomment %} <img src="{{ item.image.url }}" class="card-img-top">
            <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
            </a>
        </div>

        <div class="card-body text-center">
            <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
            </a>
            <h5>
                <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                        <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
                    </a>
                </strong>
            </h5>

            <h4 class="font-weight-bold blue-text">
                <strong>$
                    {{ item.price }}
                </strong>
            </h4>

        </div>

    </div>

</div>
{% endfor %}
</div>

</section>
<!--Section: Products v.3-->

<!--Pagination-->

{% if is_paginated %}
<nav class="d-flex justify-content-center wow fadeIn">
    <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
            </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

</div>
</main>

ecommerce_village_of_electron/templates/checkout.html
{% extends "base.html" %}
<!-- {% load crispy_forms_tags %} -->

{% block content %}

<main>
  <div class="container wow fadeIn">
    <h2 class="my-5 h2 text-center">Checkout form</h2>
    <div class="row">
      <div class="col-md-8 mb-4">
        <div class="card">
          <form method="POST" class="card-body">
            {% csrf_token %}

            <h3>Shipping address</h3>

            <div class='hideable_shipping_form'>

              <div class="md-form mb-5">
                <input type='{{form.phone_number}}' placeholder='Enter your address' id='' name=''
                  class='form-control' />


              </div>



              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">City</label>
                  {{ form.city }}
                  <div class="invalid-feedback">
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="shipping_zip">Phone Number</label>
                  <input type='text' placeholder='07x xxx xxxx' id='' name='' class='{{form.phone_number}}' />

                  <div class="invalid-feedback">
                  </div>
                </div>
              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="same_billing_address"
                  id="same_billing_address">

              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_shipping"
                  id="set_default_shipping">
              </div>

            </div>




            <!-- <h3>Billing address</h3> -->

            <div class='hideable_billing_form'>




              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">

                  <div class="invalid-feedback">
                  </div>
                </div>

              </div>

            </div>




            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit"> Checkout</button>

          </form>

        </div>

      </div>

      <div class="col-md-4 mb-4">
        {% include "order_snippet.html" %}
      </div>

    </div>

  </div>
</main>

{% endblock content %}

{% block extra_scripts %}
<script>
  var hideable_shipping_form = $('.hideable_shipping_form');
  var hideable_billing_form = $('.hideable_billing_form');

  var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
  var use_default_billing = document.querySelector("input[name=use_default_billing]");

  use_default_shipping.addEventListener('change', function () {
    if (this.checked) {
      hideable_shipping_form.hide();
    } else {
      hideable_shipping_form.show();
    }
  })

  use_default_billing.addEventListener('change', function () {
    if (this.checked) {
      hideable_billing_form.hide();
    } else {
      hideable_billing_form.show();
    }
  })

</script>
{% endblock extra_scripts %}

ecommerce_village_of_electron/templates/checkout11.html
{% extends "base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock content %}

ecommerce_village_of_electron/templates/home.html
{% extends "base.html" %}

{% block content %}
<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">

            <a class="nav-link" href="/category-product/L/">Laptops</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/category-product/SM/">Smart Phones</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/category-product/T/">Tablets</a>
          </li>

        </ul>
        <!-- Links -->

        <form class="form-inline" role="search" action="{% url 'core:search' %}" method="get">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <div class="row wow fadeIn">

        {% for item in object_list %}
        <div class=" col-lg-3 col-md-6 mb-4">

          <div class="card">

            <div class="view overlay">
              {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                class="card-img-top" {% endcomment %} <img src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                    <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>$
                  {{ item.price }}
                </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}
      </div>

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

  </div>
</main>

{% endblock content %}

ecommerce_village_of_electron/templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="/">
      <strong class="blue-text">Village of Electron</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        {% comment %} <li class="nav-item active">
          <a class="nav-link waves-effect" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
        </li> {% endcomment %}
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"> Login </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

ecommerce_village_of_electron/templates/product.html
{% extends "base.html" %}

{% block content %}

<main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

        <!--Grid row-->
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-md-6 mb-4">

                <img src="{{ object.image.url }}" class="img-fluid" alt="">

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">

                <!--Content-->
                <div class="p-4">

                    <div class="mb-3">
                        <a href="">
                            <span class="badge purple mr-1">{{ object.get_category_display }}</span>
                        </a>
                    </div>

                    <p class="lead">
                        <!-- <span class="mr-1">
                            <del>${{ object.price }}</del>
                        </span> -->
                        <span>${{ object.price }}</span>
                    </p>

                    <p class="lead font-weight-bold">Description</p>

                    <p>{{ object.description }}</p>

                    {% comment %} <form class="d-flex justify-content-left">
                        <!-- Default input -->
                        <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
                        <button class="btn btn-primary btn-md my-0 p" type="submit">
                            Add to cart
                            <i class="fas fa-shopping-cart ml-1"></i>
                        </button>

                    </form> {% endcomment %}
                    <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                        Add to cart
                        <i class="fas fa-shopping-cart ml-1"></i>
                    </a>
                    <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                        Remove from cart
                    </a>

                </div>
                <!--Content-->

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

        <hr>

        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn">

            <!--Grid column-->
            <div class="col-md-6 text-center">

                <h4 class="my-4 h4">Related Products</h4>

                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta
                    odit
                    voluptates,
                    quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row wow fadeIn">

            <!--Grid column-->
            <!-- <div class="col-lg-4 col-md-12 mb-4">

                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid"
                    alt="">

            </div> -->
            <!--Grid column-->

            <!--Grid column-->
            <!-- <div class="col-lg-4 col-md-6 mb-4">

                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid"
                    alt="">

            </div> -->
            <!--Grid column-->

            <!--Grid column-->
            <!-- <div class="col-lg-4 col-md-6 mb-4">

                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid"
                    alt="">

            </div> -->
            <!--Grid column-->

        </div>
        <!--Grid row-->

    </div>
</main>

{% endblock content %}

ecommerce_village_of_electron/templates/product222.html
{% extends "base.html" %}

{% block content %}

<main class="mt-5 pt-4">
  <!-- <div class="container dark-grey-text mt-5"> -->

  <!--Grid row-->
  <div class="row wow fadeIn">

    <!--Grid column-->
    <div class="col-md-6 mb-4">

      <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt=""> -->
      <img src="{{ object.image.url }}" class="img-fluid" alt="">

    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-md-6 mb-4">

      <!--Content-->
      <div class="p-4">

        <div class="mb-3">
          <a href="">
            <span class="badge purple mr-1">{{ object.get_category_display }}</span>
          </a>
        </div>

        <p class="lead">
          <!-- {% if object.discount_price %} -->
          <span class="mr-1">
            <del>${{ object.price }}</del>
          </span>
          <!-- <span>${{ object.discount_price }}</span> -->
          <!-- {% else %} -->
          <span>${{ object.price }}</span>
          <!-- {% endif %} -->
        </p>

        <p class="lead font-weight-bold">Description</p>

        <p>{{ object.description }}</p>

        {% comment %} <form class="d-flex justify-content-left">
          <!-- Default input -->
          <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
          <button class="btn btn-primary btn-md my-0 p" type="submit">
            Add to cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </button>

        </form> {% endcomment %}
        <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
          Add to cart
          <i class="fas fa-shopping-cart ml-1"></i>
        </a>
        <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
          Remove from cart
        </a>

      </div>
      <!--Content-->

    </div>
    <!--Grid column-->

  </div>
  <!--Grid row-->
  <div class="row wow fadeIn">

    <!--Grid column-->


  </div>
  <!--Grid column-->

  <style>
    img {
      border: 1px solid #ddd;
      /* Gray border */
      border-radius: 4px;
      /* Rounded border */
      padding: 5px;
      /* Some padding */
      width: 150px;
      /* Set a small width */
    }

    /* Add a hover effect (blue shadow) */
    img:hover {
      box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
    }
  </style>



  </body>

  <!--Grid column-->

  </div>

  <!--Grid column-->

  <!--Grid column-->


  <!--Grid column-->

  <hr>


  <!--Grid column-->
  <!-- <!-- <div class="col-md-6 text-center"> -->

  <h4 class="my-4 h4">Additional information</h4>

  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
    voluptates,
    quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

  </div> -->
  <!--Grid column-->

  <!-- </div> -->
  <!--Grid row-->

  <!--Grid row-->

  <!--Grid row

  </div>
</main>

{% endblock content %}

ecommerce_village_of_electron/templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>

ecommerce_village_of_electron/templates/search.html
{% extends "home.html" %}


{% for item in object_list %}
<div class="col-lg-3 col-md-6 mb-4">

    <div class="card">

        <div class="view overlay">
            {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                class="card-img-top" {% endcomment %} <img src="{{ item.image.url }}" class="card-img-top">
            <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
            </a>
        </div>

        <div class="card-body text-center">
            <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
            </a>
            <h5>
                <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                        <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
                    </a>
                </strong>
            </h5>

            <h4 class="font-weight-bold blue-text">
                <strong>$
                    {{ item.price }}
                </strong>
            </h4>

        </div>

    </div>

</div>
{% endfor %}
</div>

</section>
<!--Section: Products v.3-->

<!--Pagination-->

{% if is_paginated %}
<nav class="d-flex justify-content-center wow fadeIn">
    <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
            </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

</div>
</main>

ecommerce_village_of_electron/templates/thank_you.html
{% extends "base.html" %}


{% block content %}

{<h1 mahmoud></h1>}
{% endblock content %}